language: objective-c
osx_image: xcode9
xcode_project: Client.xcodeproj
xcode_scheme: Client
xcode_sdk: macosx10.12

script:
- xcodebuild clean build test -project "Client.xcodeproj" -scheme "Client" -destination 'generic/platform=macOS'

after_success:
- bash <(curl -s https://codecov.io/bash)
